name: eleicao_representante
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.4
  flutter_acrylic: ^1.0.0+2
  bitsdojo_window: ^0.1.1+1
  cloud_firestore: ^3.1.18
  firedart: ^0.9.0+1
  fluent_ui: ^3.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 500
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 400
  assets:
    - assets/images/logo.png

  uses-material-design: true
